-- Users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null unique,
  name varchar(100) not null,
  role varchar(50) not null
);
